### ISSUE TITLE
Plan for 1.17

### ISSUE THREAD

**Issue by cech12** [alcatrazEscapee/mcjunitlib#4]
Hey!

I love this testing library! I started to port my mods to 1.17 and I miss the test aspects^^
So here is my question: Are there any plans of porting this library to support 1.17? 
Maybe I could support you doing this. 

Greetings
Chris

**Comment by alcatrazEscapee** [comment]
No, because Mojang's official gametest system is now available to modders and I am planning to switch to that as soon as it is usable. You can see a (currently working) example of the gametest system setup on Fabric, courtesy of [2No2Name](https://github.com/2No2Name/McTester). But forge has every intent to eventually support using the gametest system as well for modders. From the [2021 Forge Annual Parley](https://gist.github.com/TheCurle/2faae1dbce2819fbe3beda154a53340b):

> **Will the gametest system, included in 1.17, be supported by Forge for use? (e.g., Forge will work to make it usable for mods, consider PRs targeted at it, extend it, etc.) In the same fashion that Forge has adopted Mojang's data generators?**
> - Yes. It's an awesome system, and running unit tests in world is awesome.
> - We're going to automate it into PRs and releases to verify that no expected behavior is broken.
> - If someone wants to contribute a framework for testing a "shitload" of vanilla features, feel free.

If/when I get some time I might look into seeing what is required to get game tests working on 1.17 myself, or seeing how the vanilla system works. Or someone else gets to it before me.

So in essence, 1.16 will (hopefully) be the last version for mcjunitlib. There is a possibility of keeping the unit test mechanics, (i.e. the JUnit test running) extracted, but only time will tell.

### Update 2021-08-31

- Forge has WIP support for the gametest system: 
  - https://github.com/MinecraftForge/MinecraftForge/pull/8024
- Modlauncher and Bootstrap Launcher updates have made it *an absolute pain in the \*\*\** to hook into in the same place to run JUnit tests. So this is likely not going to happen.
- Other options:
  - JUnit test actions, within the gradle `test` task. Pros: works, IDE integration. Cons: low coverage due to class loading issues.
  - Runtime validations, only enabled when run when in IDE. This is actually used in various places in Minecraft to test various things. [Example in TFC](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/8876f2c137c9b284fc9628ef2c37455f0619a2ed/src/main/java/net/dries007/tfc/common/tileentity/TFCTileEntities.java#L64).
  - Just writing them as game tests.

**Comment by cech12** [comment]
Thanks for your detailed answer! That system sounds great! Maybe I will look into that, too :)

**Comment by cech12** [comment]
Since Minecraft Forge 1.18.1-39.0.88 the gametest library is supported. This issue can be closed. :)

Here are some useful links:
- [How to use the Game Test Framework on Forge](https://gist.github.com/SizableShrimp/60ad4109e3d0a23107a546b3bc0d9752)
- https://github.com/MinecraftForge/MinecraftForge/pull/8225
